name: Check Markdown links
on: push
jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.5
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.15
        with:
          folder-path: "docs"
